### ISSUE TITLE
SCR deploy error 

### ISSUE THREAD

**Issue by RoberttsengTAO** [sassoftware/sas-container-runtime#1]
Hi expert, 
I have some questions about SCR.
My Env is SAS Viya stable 2021.2.3.
When I published SCR,  it returned error.
 Retrieving image manifest k8bastion01:5000/viya-4-x64_oci_linux_2-docker/sas-decisions-runtime-base:1.14.26-20220114.1642173673028 \n\u001b[36mINFO\u001b[0m[0003] Retrieving image k8bastion01:5000/viya-4-x64_oci_linux_2-docker/sas-decisions-runtime-base:1.14.26-20220114.1642173673028 from registry k8bastion01:5000 \nerror building image: Get \"https://k8bastion01:5000/v2/\": dial tcp: lookup k8bastion01 on 10.96.0.10:53: no such host
how to fix this?
Many thanks
Robert

**Comment by devaKumaraswamy** [comment]
Robert:
Sorry to pass this on:
Please contact SAS Technical Support.
 SCR is a fully supported product and they can help you out.

**Comment by jebatc** [comment]
Marking this issue as closed.  Hopefully the issue has been reported to SAS technical support and resolved by now.
